=== benhmali/SEPA/src/main/resources/sepa.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://univ.fr/sepa" xmlns="http://univ.fr/sepa">

	<xs:element name="Document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DrctDbtTxInf" type="DrctDbtTxInfType"
					minOccurs="1" maxOccurs="10" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="DrctDbtTxInfType">
		<xs:sequence>
			<xs:element name="PmtId" type="Max35Text" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="InstdAmt" type="Amount" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="DrctDbtTx" type="CmpsdTx" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="DbtrAgt" type="CmpsdAgt" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="Dbtr" type="CmpsdNmd" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="DbtrAcct" type="CmpsdIdt" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="RmtInf" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="Max35Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="35" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Amount">
		<xs:sequence>
			<xs:element name="InstdAmt" type="xs:float" />
		</xs:sequence>
		<xs:attribute name="Ccy" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="CmpsdTx">
		<xs:sequence>
			<xs:element name="MndtId" type="Max35Text" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="DtOfSgntr" type="xs:date" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CmpsdAgt">
		<xs:choice>
			<xs:element name="BIC" type="BICType" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="Othr" type="OthrType" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="OthrType">
		<xs:sequence>
			<xs:element name="Id" type="Max35Text" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="BICType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{4,4}[A-Z]{2,2}[A-Z]{2,2}([A-Z]{3,3}){0,1}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="CmpsdNmd">
		<xs:sequence>
			<xs:element name="NM" type="Max35Text" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CmpsdIdt">
		<xs:choice>
			<xs:element name="IBAN" type="IBANType" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="PrvtId">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="othr" type="OthrType" minOccurs="1" maxOccurs="1" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:simpleType name="IBANType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{2,2}[0-9]{2,2}[A-Z0-9]{1,30}" />
		</xs:restriction>
	</xs:simpleType>


</xs:schema>

=== benhmali/SEPA/target/classes/sepa.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Document xmlns:p="http://univ.fr/sepa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/sepa sepa.xsd ">
  <DrctDbtTxInf>
    <PmtId>PmtId</PmtId>
    <InstdAmt Ccy="">
      <InstdAmt>0.0</InstdAmt>
    </InstdAmt>
    <DrctDbtTx>
      <MndtId>MndtId</MndtId>
      <DtOfSgntr>2001-01-01</DtOfSgntr>
    </DrctDbtTx>
    <DbtrAgt>
      <BIC>AZAZBBAZAEA</BIC>
    </DbtrAgt>
    <Dbtr>
      <NM>NM</NM>
    </Dbtr>
    <DbtrAcct>
      <IBAN>AZ21AZEZRCVS52265</IBAN>
    </DbtrAcct>
  </DrctDbtTxInf>
</p:Document>

=== benhmali/SEPA/src/main/resources/sepa1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="http://univ.fr/sepa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/sepa sepa.xsd ">
  <DrctDbtTxInf>
    <PmtId>REF OPE BBBB</PmtId>
    <InstdAmt Ccy="EUR">
      <InstdAmt>2150.0</InstdAmt>
    </InstdAmt>
    <DrctDbtTx>
      <MndtId>MndtId</MndtId>
      <DtOfSgntr>2001-01-01</DtOfSgntr>
    </DrctDbtTx>
    <DbtrAgt>
      <BIC>BANKGBULAAA</BIC>
    </DbtrAgt>
    <Dbtr>
      <NM>NM</NM>
    </Dbtr>
    <DbtrAcct>
      <IBAN>>GB29NWBK1331926819</IBAN>
    </DbtrAcct>
  </DrctDbtTxInf>
</Document>
